### ISSUE TITLE
Add templates for better maintaining 

### ISSUE THREAD

**Issue by Dun-sin** [soul-project/soul#142]
I saw this project is open to contributions, and it doesn't have Pull request and issue templates, it makes it easier for you to maintain your projects.

Here are links for reference: 
[Pull Request Template](https://learn.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops)
[Pull Request and Issue Template](https://bakingclouds.com/multiple-template-choices/)

**Comment by lws803** [comment]
Good call! 😄 thanks for the callout, I'll look into adding these as well as the contributing doc later
