### ISSUE TITLE
[DOCS] separate commands

### ISSUE THREAD

**Issue by Dun-sin** [soul-project/soul#144]
I think it's better to separate the commands for installing this project, so it can be easy to copy.
For example:
```
npm install
```

```
npm start
```

![image](https://user-images.githubusercontent.com/78784850/195772197-fa294b69-8026-4be3-9932-db5592a928fd.png)

> I don't need to work on this, anyone can, if you think the change is worth working one

**Comment by lws803** [comment]
Resolved as of [[NO-REF] Fix issue template and readme](https://github.com/soul-project/soul/pull/147#top)
